name: Manual Deployment
on:
        workflow_dispatch

jobs:
        deploy:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout code
                          uses: actions/checkout@v2

                        - name: Login to Azure
                          uses: azure/login@v1
                          with:
                            client-id: ${{ secrets.AZURE_CLIENT_ID }}
                            tenant-id: ${{ secrets.TENANT_ID }}
                            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                            enable-AzPSSession: true

                        - name: Deploy ARM Template
                          uses: Azure/arm-deploy@v1
                          with:
                            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                            resourceGroupName: ${{ secrets.AZURE_RG }}
                            template: ./InfrastructureAsCode/main.bicep
                            parameters: environment=${{ env.targetEnv }}