on:
  workflow_dispatch:
   inputs:
    appenv:
      type: choice
      description: Choose the target environment
      options: 
        - dev
        - test
        - prod

    permissions:
    id-token: write
    contents: read

  # The overall workflow name will be Azure Bicep. This will show up in the
  # GitHub Action page.
  name: Azure Bicep
  jobs:
    # This script has one job: build and deploy the IaC resources
    build-and-deploy:
      # We run this on an Ubuntu-based GitHub hosted runner. This hosted runner
      # has certain software already installed, including az cli
      runs-on: ubuntu-latest
      steps:
      # Check out the code. This grabs code from the repository and
      # makes it available to the GitHub hosted runner. It will usually be the
      # first task for any workflow
      - uses: actions/checkout@main

        # Log into Azure using a federated credential. We have already set up the
        # federation process in a prior step, so we need to pass in the following:
        # Client ID = Application registration ID
        # Tenant ID = Application owner organization ID (previously called Tenant ID in Azure)
        # Subscription ID
        # https://github.com/azure/login
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
         # enable-AzPSSession: true

        # Deploy ARM template
      - name: Run ARM deploy
        # https://github.com/azure/arm-deploy
        uses: azure/arm-deploy@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          resourceGroupName: rg-devops-techexcel-lab
          template: ./InfrastructureAsCode/main.bicep
          # Use the environment variable called targetEnv
          parameters: environment=${{ env.targetEnv }}
