#
# First Workflow for this repo and the workshop exercises
#
name: First Workflow


on:
  workflow_dispatch:
  issues:
    types: [opened]

# 
# Workflow jobs.
#
jobs:
  #
  # Execute first job
  # 
  job-one:
    # 
    # Execute first job on GitHub-hosted Ubuntu machine
    #
    runs-on: ubuntu-latest

    # 
    # Steps to execute for the first job
    #
    steps:
    - name: Step One
      # 
      # Run command in a bash shell script.
      #
      run: echo "Log from Step ${STEP_ONE}"
      # 
      # Run command with the variable defined below.
      #
      env:
        STEP_ONE: One
    - name: Step two
      # 
      # Run command in a bash shell script.
      #
      run: echo "Log from Step ${STEP_TWO}"
      # 
      # Run command with the variable defined below.
      #
      env:
        STEP_TWO: Two
      
  job-two:
    # 
    # Second job is dependent on First job. It will only run after First job completes.
    # 
    needs: job-one
    # 
    # Execute second job on GitHub-hosted Ubuntu machine
    #
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      # 
      # Execute the Cowsays GitHub action.
      # 
      uses: mscoutermarsh/cowsays-action@master
      # The 'with' block includes parameters that the workflow will pass
      # to this action. Parameters are all in key-value format.
      with:
        text: ${{ env.TEXT }}
        color: 'magenta'
      env:
        TEXT: 'Ready for prod--ship it!'